name: careerpilot_ai_new
description: "CareerPilot AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.2.2
  url_launcher: ^6.3.2
  internet_connection_checker_plus: ^3.1.2

  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/careerpilot_logo.png

flutter_native_splash:
  color: "#0B1020"
  image: assets/images/careerpilot_logo.png

  android_12:
    color: "#0B1020"
    image: assets/images/careerpilot_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/careerpilot_logo.png"
  adaptive_icon_background: "#0B1020"
  adaptive_icon_foreground: "assets/images/careerpilot_logo.png"
  min_sdk_android: 21