// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Platform not configured.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8uQrt04agSL269EgSf5_xT9S0v5klzw',
    appId: '1:655860222807:web:dbe8caadb060b224128c12',
    messagingSenderId: '655860222807',
    projectId: 'careerpilot-ai-d3faa',
    authDomain: 'careerpilot-ai-d3faa.firebaseapp.com',
    storageBucket: 'careerpilot-ai-d3faa.firebasestorage.app',
    measurementId: 'G-01VDD0JE6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEChNKzFxuEDvghiulrsGuctwyycKlCE',
    appId: '1:655860222807:android:21907d19dc94d317128c12',
    messagingSenderId: '655860222807',
    projectId: 'careerpilot-ai-d3faa',
    storageBucket: 'careerpilot-ai-d3faa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-RAPlSuS1Ya_7HT97IkXX-eqtjc8hVV8',
    appId: '1:655860222807:ios:bddad54c70c7e668128c12',
    messagingSenderId: '655860222807',
    projectId: 'careerpilot-ai-d3faa',
    storageBucket: 'careerpilot-ai-d3faa.firebasestorage.app',
    androidClientId:
    '655860222807-v1rb5vkfjvbob7i4usa8s4h40o8rj3nj.apps.googleusercontent.com',
    iosClientId:
    '655860222807-hq31hqnuptq054ec0hj2444ppqpsb42m.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerpilotAiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-RAPlSuS1Ya_7HT97IkXX-eqtjc8hVV8',
    appId: '1:655860222807:ios:bddad54c70c7e668128c12',
    messagingSenderId: '655860222807',
    projectId: 'careerpilot-ai-d3faa',
    storageBucket: 'careerpilot-ai-d3faa.firebasestorage.app',
    androidClientId:
    '655860222807-v1rb5vkfjvbob7i4usa8s4h40o8rj3nj.apps.googleusercontent.com',
    iosClientId:
    '655860222807-hq31hqnuptq054ec0hj2444ppqpsb42m.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerpilotAiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX8uQrt04agSL269EgSf5_xT9S0v5klzw',
    appId: '1:655860222807:web:22504235c04e113e128c12',
    messagingSenderId: '655860222807',
    projectId: 'careerpilot-ai-d3faa',
    authDomain: 'careerpilot-ai-d3faa.firebaseapp.com',
    storageBucket: 'careerpilot-ai-d3faa.firebasestorage.app',
    measurementId: 'G-1Q540CWS4V',
  );
}